export const INCREASE_INTEGER_VALUE = "INCREASE_INTEGER_VALUE";
export const ADD_TODO = "ADD_TODO";
export const ADD_TODOS = "ADD_TODOS";
export const FILTER_THE_LIST = "FILTER_THE_LIST"
export const TOGGLE_TODO_STATUS = "TOGGLE_TODO_STATUS"
export const EDIT_TODO = "EDIT_TODO"